[build-system]
requires = [
  "setuptools>=42",
  "py2app",
  "wheel",
  "quickmacapp",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.ruff]

ignore = [
  "E731",
]
