#!/bin/bash -ex

mypy ./src;
rm -fr ./dist;

# https://github.com/ronaldoussoren/py2app/issues/444
python setup.py py2app | cat;

cd dist;

BUNDLE_ID='im.glyph.and.this.is.pomodouroboros';
NAME='Pomodouroboros';

# set IDENTITY and USERNAME
. "${HOME}/.signing-vars.sh";

find "${NAME}.app" -iname '*.so' -or -iname '*.dylib' |
    while read libfile; do
        codesign --sign "${IDENTITY}" \
                 --entitlements ../python-entitlements.plist \
                 --deep "${libfile}" \
                 --force \
                 --options runtime;
    done;

codesign --sign "${IDENTITY}" \
         --entitlements ../python-entitlements.plist \
         --deep "${NAME}.app" \
         --force \
         --options runtime;

zip -yr \
    "${NAME}.app.zip" \
    "${NAME}.app";

# To avoid the need for authentication:
# xcrun altool --store-password-in-keychain-item NOTARIZE_KEY \
#   -u "${USERNAME}" \
#   -p "$(osascript -e 'return text returned of (display dialog "pw" default answer "" with hidden answer)')"

xcrun altool \
      --notarize-app \
      --file "${NAME}.app.zip" \
      --type osx \
      --username "${USERNAME}" \
      --password "@keychain:NOTARIZE_KEY" \
      --primary-bundle-id="${BUNDLE_ID}";

read 'ignored?Hit enter when notarization is ready: ';

xcrun stapler staple "./${NAME}.app";
zip -qyr "${NAME}.notarized.app.zip" "${NAME}.app";
