#!/bin/zsh -ex

mypy ./src;
rm -fr ./dist;

# https://github.com/ronaldoussoren/py2app/issues/444
python setup.py py2app | cat;

cd dist;

BUNDLE_ID='im.glyph.and.this.is.pomodouroboros';
NAME='Pomodouroboros';

# set IDENTITY and NOTARIZE_USERNAME
. "${HOME}/.signing-vars.sh";

find "${NAME}.app" -iname '*.so' -or -iname '*.dylib' |
    while read libfile; do
        codesign --sign "${IDENTITY}" \
                 --entitlements ../python-entitlements.plist \
                 --deep "${libfile}" \
                 --force \
                 --options runtime;
    done;

codesign --sign "${IDENTITY}" \
         --entitlements ../python-entitlements.plist \
         --deep "${NAME}.app" \
         --force \
         --options runtime;

zip -yr \
    "${NAME}.app.zip" \
    "${NAME}.app";

xcrun notarytool submit \
      "${NAME}.app.zip" \
      --apple-id="glyf@me.com"
      --wait

xcrun stapler staple "./${NAME}.app";

zip -qyr "${NAME}.notarized.app.zip" "${NAME}.app";
