#!/bin/bash -ex

#mypy ./src;
rm -fr ./build ./dist;
# https://github.com/ronaldoussoren/py2app/issues/444
python setup.py py2app --alias | cat;
rm -fr ./build;
exec ./dist/Pomodouroboros.app/Contents/MacOS/Pomodouroboros;
